baseURL: https://ydorji-portfolio.netlify.app/
languageCode: en-us
title: Portfolio Website Yugyel 
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      This is for you, my fans. Thank you all.
    title: Hi, my name is Yugyel and this is my website
  blog: {}
  contact:
    address:
      - city: London 
        country: United Kingdom
        street: London Business School
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: ydorji.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: 
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social: 
      - icon: fa-twitter
        label: Twitter
        url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/yuli.dorji/
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/yulidorji/
      - icon: fa-github
        label: GitHub
        url: https://www.github.com/dorjiyugyel
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/yulidorji
      - icon: fa-youtube
        label: Youtube
        url: https://www.youtube.com/watch?v=dQw4w9WgXcQ
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: picture.jpg
        subtitle: A little background on my jouney so far
        title: About Me
        url: blogs/bio.html
      - image: NYC.jpg
        subtitle: CV
        title: Education and Working Experience
        url: '/files/YugyelDorjiResume.pdf'
      - image: Thimphu.jpg
        subtitle: Lorem Etiam Nullam
        title: Magna
        url: blogs/magna
      - image: Golf.jpg
        subtitle: I love golf but golf doesn't love me :(
        title: Ipsum
        url: blogs/ipsum
      - image: poker.jpg
        subtitle: Everybody loves a little gamble 
        title: Poker
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "We're no strangers to love. \r\n You know the rules and so do I. \r\n 
    A full commitment's what I'm thinking of. \r\n  You wouldn't get this from any other guy. \r\n 
    I just wanna tell you how I'm feeling. \r\n Gotta make you understand. \r\n
    Never gonna give you up, never gonna let you down. \r\n Never gonna turn around and 
    desert you. \r\n"
    title: Never Ever
    url: blogs
